# Generated by Django 5.2.8 on 2025-11-09 10:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(unique=True)),
                ('draw_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-round_no'],
            },
        ),
        migrations.CreateModel(
            name='WinningNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=50)),
                ('bonus', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winning', to='lotto.round')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numbers', models.CharField(max_length=50)),
                ('match_status', models.CharField(default='미추첨', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto.round')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('round', 'name', 'numbers')},
            },
        ),
    ]
