# Generated by Django 5.2.8 on 2025-11-11 04:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('draw_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='추첨일')),
            ],
            options={
                'verbose_name': '추첨 회차',
                'verbose_name_plural': '추첨 회차',
                'db_table': 'lotto_round',
                'ordering': ['-round_no'],
            },
        ),
        migrations.RemoveField(
            model_name='winningnumber',
            name='round',
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('numbers', models.CharField(max_length=30, verbose_name='선택 번호(정렬된 6개)')),
                ('result_rank', models.CharField(db_column='match_status', default='미추첨', max_length=10, verbose_name='등수/상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='구매 시각')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto.drawround', verbose_name='회차')),
            ],
            options={
                'verbose_name': '사용자 티켓',
                'verbose_name_plural': '사용자 티켓',
                'db_table': 'lotto_lottoticket',
                'ordering': ['-created_at'],
                'unique_together': {('round', 'name', 'numbers')},
            },
        ),
        migrations.CreateModel(
            name='WinningSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=30, verbose_name='본번호(정렬된 6개)')),
                ('bonus', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)], verbose_name='보너스')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winning_set', to='lotto.drawround', verbose_name='회차')),
            ],
            options={
                'verbose_name': '당첨번호 세트',
                'verbose_name_plural': '당첨번호 세트',
                'db_table': 'lotto_winningnumber',
            },
        ),
        migrations.DeleteModel(
            name='LottoTicket',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='WinningNumber',
        ),
    ]
