# Generated by Django 5.2.8 on 2025-11-11 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0002_drawround_remove_winningnumber_round_userticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winningset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 시각'),
            preserve_default=False,
        ),
    ]
